### PR TITLE
add Chromium to the docker image

### PR DESCRIPTION
**Pull request by PeteBoucher**
Is this what you had in mind?

Running
```
docker build -t zeochrome .
docker run -p 8000:8000 zeochrome:latest
```
allows zeo to startup with no "missing Chrome" warning.

I can connect to the world via port 8000 of my docker-machine but nothing renders, just black controllers on white bg.

Copy pasted to the dockerfile from https://github.com/dockerfile/chrome/blob/master/Dockerfile

### CODE REVIEW

**Comment by avaer** [comment]
Thanks for this! Works well, and good call on copying out of the official Dockerfile.

I'd love to debug what you're seeing though -- couldn't reproduce here on `master`. Looks like the core is serving but default plugins aren't loading. There might be some console output that solves the mystery, if you could paste it.

cap

Any log output from the server would also be helpful in case it's a backend crash.

**Comment by PeteBoucher** [comment]
Thanks for the merge, may be able to cleanup the Dockerfile by merging all the apt-get inastalls into one line. Not sure if `apt-get clean` and `rm -rf /var/lib/apt/lists/*` do the same job.

I get nothing in the console but Chrome Debugger pauses on an Exception. Is that because I don't have a head mounted display? 
image
image

**Comment by PeteBoucher** [comment]
On further exploration I found the E key brings up a menu panel
image
Perhaps my docker network setup is preventing the world from loading?

**Comment by avaer** [comment]
Yeah, whether you've got an HMD/WebVR should have no impact on the ability to connect to or use the app.

Do you have "break on exception" mode set in Chrome? That could be it. https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints#exceptions

There's a failing blockchain request made on startup -- but from that screenshot it looks like that failing request causes a break into debugger (possibly halting the loading process entirely) whereas on my machine it harmlessly fails the request and continues to load fine.

**Comment by avaer** [comment]
Regardless I think there's a bug here, which is that there's a toplevel uncaught promise in the blockchain engine. If that were caught properly I suspect the browser wouldn't be breaking into debugger at all.

Will push a fix for that.

EDIT: pushed https://github.com/modulesio/zeo/commit/ecf9a35b1c71429b27d022c8d387a1c53070bcfa

**Comment by PeteBoucher** [comment]
Turned off break on exceptions in Chrome debugger, no change. Also tried loading it in Firefox to the same effect, albeit with more Console output:
image

**Comment by avaer** [comment]
Ooh, that is useful. Shader errors.

Would you be able to paste that log output as text?

**Comment by PeteBoucher** [comment]
```
unreachable code after return statement[Learn More]  _core_engines_wallet.js:965:12
TypeError: NetworkError when attempting to fetch resource.  _core_engines_zeo.js:136:15
THREE.WebGLRenderer 86  three.js:20352:3
Error: WebGL warning: Disallowing antialiased backbuffers due to blacklisting.  three.js:20536:22
THREE.WebGLShader: gl.getShaderInfoLog() vertex WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshPhongMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define USE_FOG
8: #define FOG_EXP2
9: #define BONE_TEXTURE
10: #define NUM_CLIPPING_PLANES 0
11: uniform mat4 modelMatrix;
12: uniform mat4 modelViewMatrix;
13: uniform mat4 projectionMatrix;
14: uniform mat4 viewMatrix;
15: uniform mat3 normalMatrix;
16: uniform vec3 cameraPosition;
17: attribute vec3 position;
18: attribute vec3 normal;
19: attribute vec2 uv;
20: #ifdef USE_COLOR
21: 	attribute vec3 color;
22: #endif
23: #ifdef USE_MORPHTARGETS
24: 	attribute vec3 morphTarget0;
25: 	attribute vec3 morphTarget1;
26: 	attribute vec3 morphTarget2;
27: 	attribute vec3 morphTarget3;
28: 	#ifdef USE_MORPHNORMALS
29: 		attribute vec3 morphNormal0;
30: 		attribute vec3 morphNormal1;
31: 		attribute vec3 morphNormal2;
32: 		attribute vec3 morphNormal3;
33: 	#else
34: 		attribute vec3 morphTarget4;
35: 		attribute vec3 morphT[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshPhongMaterial
4: #define GAMMA_FACTOR 2
5: #define USE_FOG
6: #define FOG_EXP2
7: #define NUM_CLIPPING_PLANES 0
8: #define UNION_CLIPPING_PLANES 0
9: uniform mat4 viewMatrix;
10: uniform vec3 cameraPosition;
11: #define TONE_MAPPING
12: #define saturate(a) clamp( a, 0.0, 1.0 )
13: uniform float toneMappingExposure;
14: uniform float toneMappingWhitePoint;
15: vec3 LinearToneMapping( vec3 color ) {
16: 	return toneMappingExposure * color;
17: }
18: vec3 ReinhardToneMapping( vec3 color ) {
19: 	color *= toneMappingExposure;
20: 	return saturate( color / ( vec3( 1.0 ) + color ) );
21: }
22: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
23: vec3 Uncharted2ToneMapping( vec3 color ) {
24: 	color *= toneMappingExposure;
25: 	return saturate( Uncharted2Helper( color ) / Uncharted2Helper( vec3( toneMapping[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() vertex WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshPhongMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define USE_FOG
8: #define FOG_EXP2
9: #define USE_MAP
10: #define USE_SPECULARMAP
11: #define BONE_TEXTURE
12: #define NUM_CLIPPING_PLANES 0
13: uniform mat4 modelMatrix;
14: uniform mat4 modelViewMatrix;
15: uniform mat4 projectionMatrix;
16: uniform mat4 viewMatrix;
17: uniform mat3 normalMatrix;
18: uniform vec3 cameraPosition;
19: attribute vec3 position;
20: attribute vec3 normal;
21: attribute vec2 uv;
22: #ifdef USE_COLOR
23: 	attribute vec3 color;
24: #endif
25: #ifdef USE_MORPHTARGETS
26: 	attribute vec3 morphTarget0;
27: 	attribute vec3 morphTarget1;
28: 	attribute vec3 morphTarget2;
29: 	attribute vec3 morphTarget3;
30: 	#ifdef USE_MORPHNORMALS
31: 		attribute vec3 morphNormal0;
32: 		attribute vec3 morphNormal1;
33: 		attribute vec3 morphNormal2;
34: 		attribute vec3 morphNormal3;
35: 	#else
36: 		attribut[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshPhongMaterial
4: #define GAMMA_FACTOR 2
5: #define USE_FOG
6: #define FOG_EXP2
7: #define USE_MAP
8: #define USE_SPECULARMAP
9: #define NUM_CLIPPING_PLANES 0
10: #define UNION_CLIPPING_PLANES 0
11: uniform mat4 viewMatrix;
12: uniform vec3 cameraPosition;
13: #define TONE_MAPPING
14: #define saturate(a) clamp( a, 0.0, 1.0 )
15: uniform float toneMappingExposure;
16: uniform float toneMappingWhitePoint;
17: vec3 LinearToneMapping( vec3 color ) {
18: 	return toneMappingExposure * color;
19: }
20: vec3 ReinhardToneMapping( vec3 color ) {
21: 	color *= toneMappingExposure;
22: 	return saturate( color / ( vec3( 1.0 ) + color ) );
23: }
24: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
25: vec3 Uncharted2ToneMapping( vec3 color ) {
26: 	color *= toneMappingExposure;
27: 	return saturate( Uncharted2Helpe[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() vertex WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshBasicMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define USE_FOG
8: #define FOG_EXP2
9: #define BONE_TEXTURE
10: #define NUM_CLIPPING_PLANES 0
11: uniform mat4 modelMatrix;
12: uniform mat4 modelViewMatrix;
13: uniform mat4 projectionMatrix;
14: uniform mat4 viewMatrix;
15: uniform mat3 normalMatrix;
16: uniform vec3 cameraPosition;
17: attribute vec3 position;
18: attribute vec3 normal;
19: attribute vec2 uv;
20: #ifdef USE_COLOR
21: 	attribute vec3 color;
22: #endif
23: #ifdef USE_MORPHTARGETS
24: 	attribute vec3 morphTarget0;
25: 	attribute vec3 morphTarget1;
26: 	attribute vec3 morphTarget2;
27: 	attribute vec3 morphTarget3;
28: 	#ifdef USE_MORPHNORMALS
29: 		attribute vec3 morphNormal0;
30: 		attribute vec3 morphNormal1;
31: 		attribute vec3 morphNormal2;
32: 		attribute vec3 morphNormal3;
33: 	#else
34: 		attribute vec3 morphTarget4;
35: 		attribute vec3 morphT[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshBasicMaterial
4: #define GAMMA_FACTOR 2
5: #define USE_FOG
6: #define FOG_EXP2
7: #define NUM_CLIPPING_PLANES 0
8: #define UNION_CLIPPING_PLANES 0
9: uniform mat4 viewMatrix;
10: uniform vec3 cameraPosition;
11: #define TONE_MAPPING
12: #define saturate(a) clamp( a, 0.0, 1.0 )
13: uniform float toneMappingExposure;
14: uniform float toneMappingWhitePoint;
15: vec3 LinearToneMapping( vec3 color ) {
16: 	return toneMappingExposure * color;
17: }
18: vec3 ReinhardToneMapping( vec3 color ) {
19: 	color *= toneMappingExposure;
20: 	return saturate( color / ( vec3( 1.0 ) + color ) );
21: }
22: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
23: vec3 Uncharted2ToneMapping( vec3 color ) {
24: 	color *= toneMappingExposure;
25: 	return saturate( Uncharted2Helper( color ) / Uncharted2Helper( vec3( toneMapping[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() vertex WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshPhongMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define USE_FOG
8: #define FOG_EXP2
9: #define FLAT_SHADED
10: #define BONE_TEXTURE
11: #define NUM_CLIPPING_PLANES 0
12: uniform mat4 modelMatrix;
13: uniform mat4 modelViewMatrix;
14: uniform mat4 projectionMatrix;
15: uniform mat4 viewMatrix;
16: uniform mat3 normalMatrix;
17: uniform vec3 cameraPosition;
18: attribute vec3 position;
19: attribute vec3 normal;
20: attribute vec2 uv;
21: #ifdef USE_COLOR
22: 	attribute vec3 color;
23: #endif
24: #ifdef USE_MORPHTARGETS
25: 	attribute vec3 morphTarget0;
26: 	attribute vec3 morphTarget1;
27: 	attribute vec3 morphTarget2;
28: 	attribute vec3 morphTarget3;
29: 	#ifdef USE_MORPHNORMALS
30: 		attribute vec3 morphNormal0;
31: 		attribute vec3 morphNormal1;
32: 		attribute vec3 morphNormal2;
33: 		attribute vec3 morphNormal3;
34: 	#else
35: 		attribute vec3 morphTarget4;
36:[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: #extension GL_OES_standard_derivatives : enable
2: precision highp float;
3: precision highp int;
4: #define SHADER_NAME MeshPhongMaterial
5: #define GAMMA_FACTOR 2
6: #define USE_FOG
7: #define FOG_EXP2
8: #define FLAT_SHADED
9: #define NUM_CLIPPING_PLANES 0
10: #define UNION_CLIPPING_PLANES 0
11: uniform mat4 viewMatrix;
12: uniform vec3 cameraPosition;
13: #define TONE_MAPPING
14: #define saturate(a) clamp( a, 0.0, 1.0 )
15: uniform float toneMappingExposure;
16: uniform float toneMappingWhitePoint;
17: vec3 LinearToneMapping( vec3 color ) {
18: 	return toneMappingExposure * color;
19: }
20: vec3 ReinhardToneMapping( vec3 color ) {
21: 	color *= toneMappingExposure;
22: 	return saturate( color / ( vec3( 1.0 ) + color ) );
23: }
24: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
25: vec3 Uncharted2ToneMapping( vec3 color ) {
26: 	color *= toneMappingExposure;
27: 	retu[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() vertex WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME ShaderMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define BONE_TEXTURE
8: #define DOUBLE_SIDED
9: #define NUM_CLIPPING_PLANES 0
10: uniform mat4 modelMatrix;
11: uniform mat4 modelViewMatrix;
12: uniform mat4 projectionMatrix;
13: uniform mat4 viewMatrix;
14: uniform mat3 normalMatrix;
15: uniform vec3 cameraPosition;
16: attribute vec3 position;
17: attribute vec3 normal;
18: attribute vec2 uv;
19: #ifdef USE_COLOR
20: 	attribute vec3 color;
21: #endif
22: #ifdef USE_MORPHTARGETS
23: 	attribute vec3 morphTarget0;
24: 	attribute vec3 morphTarget1;
25: 	attribute vec3 morphTarget2;
26: 	attribute vec3 morphTarget3;
27: 	#ifdef USE_MORPHNORMALS
28: 		attribute vec3 morphNormal0;
29: 		attribute vec3 morphNormal1;
30: 		attribute vec3 morphNormal2;
31: 		attribute vec3 morphNormal3;
32: 	#else
33: 		attribute vec3 morphTarget4;
34: 		attribute vec3 morphTarget5;
35: 		attribute vec3 morphTarget6;
36: 		attribute vec3 morphTarget7;
37: 	#endif
38: #endif
39: #ifdef USE_SKINNING
40: 	attribute vec4 skinIndex;
41: 	attribute vec4 skinWeight;
42: #endif
43: 
44: varying vec2 vUv;
45: void main() {
46:   gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
47:   vUv = uv;
48: }  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME ShaderMaterial
4: #define GAMMA_FACTOR 2
5: #define DOUBLE_SIDED
6: #define NUM_CLIPPING_PLANES 0
7: #define UNION_CLIPPING_PLANES 0
8: uniform mat4 viewMatrix;
9: uniform vec3 cameraPosition;
10: #define TONE_MAPPING
11: #define saturate(a) clamp( a, 0.0, 1.0 )
12: uniform float toneMappingExposure;
13: uniform float toneMappingWhitePoint;
14: vec3 LinearToneMapping( vec3 color ) {
15: 	return toneMappingExposure * color;
16: }
17: vec3 ReinhardToneMapping( vec3 color ) {
18: 	color *= toneMappingExposure;
19: 	return saturate( color / ( vec3( 1.0 ) + color ) );
20: }
21: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
22: vec3 Uncharted2ToneMapping( vec3 color ) {
23: 	color *= toneMappingExposure;
24: 	return saturate( Uncharted2Helper( color ) / Uncharted2Helper( vec3( toneMappingWhitePoint ) ) );
25: }
26: vec3 OptimizedCineonToneMapping( vec3 color ) {
27: 	color *= toneMappingExposure;
28: 	color = max( vec3( 0.0 ), color - 0.004 );
29: 	return pow( ( color * ( 6.2 * color + 0.5 ) ) / ( color * ( 6.2 * color + 1.7 ) + 0.06 ), vec3( 2.2 ) );
30: }
31: 
32: vec3 toneMapping( vec3 color ) { return LinearToneMapping( color ); }
33: 
34: vec4 LinearToLinear( in vec4 value ) {
35: 	return value;
36: }
37: vec4 GammaToLinear( in vec4 value, in float gammaFactor ) {
38: 	return vec4( pow( value.xyz, vec3( gammaFactor ) ), value.w );
39: }
40: vec4 LinearToGamma( in vec4 value, in float gammaFactor ) {
41: 	return vec4( pow( value.xyz, vec3( 1.0 / gammaFactor ) ), value.w );
42: }
43: vec4 sRGBToLinear( in vec4 value ) {
44: 	return vec4( mix( pow( value.rgb * 0.9478672986 + vec3( 0.0521327014 ), vec3( 2.4 ) ), value.rgb * 0.0773993808, vec3( lessThanEqual( value.rgb, vec3( 0.04045 ) ) ) ), value.w );
45: }
46: vec4 LinearTosRGB( in vec4 value ) {
47: 	return vec4( mix( pow( value.rgb, vec3( 0.41666 ) ) * 1.055 - vec3( 0.055 ), value.rgb * 12.92, vec3( lessThanEqual( value.rgb, vec3( 0.0031308 ) ) ) ), value.w );
48: }
49: vec4 RGBEToLinear( in vec4 value ) {
50: 	return vec4( value.rgb * exp2( value.a * 255.0 - 128.0 ), 1.0 );
51: }
52: vec4 LinearToRGBE( in vec4 value ) {
53: 	float maxComponent = max( max( value.r, value.g ), value.b );
54: 	float fExp = clamp( ceil( log2( maxComponent ) ), -128.0, 127.0 );
55: 	return vec4( value.rgb / exp2( fExp ), ( fExp + 128.0 ) / 255.0 );
56: }
57: vec4 RGBMToLinear( in vec4 value, in float maxRange ) {
58: 	return vec4( value.xyz * value.w * maxRange, 1.0 );
59: }
60: vec4 LinearToRGBM( in vec4 value, in float maxRange ) {
61: 	float maxRGB = max( value.x, max( value.g, value.b ) );
62: 	float M      = clamp( maxRGB / maxRange, 0.0, 1.0 );
63: 	M            = ceil( M * 255.0 ) / 255.0;
64: 	return vec4( value.rgb / ( M * maxRange ), M );
65: }
66: vec4 RGBDToLinear( in vec4 value, in float maxRange ) {
67: 	return vec4( value.rgb * ( ( maxRange / 255.0 ) / value.a ), 1.0 );
68: }
69: vec4 LinearToRGBD( in vec4 value, in float maxRange ) {
70: 	float maxRGB = max( value.x, max( value.g, value.b ) );
71: 	float D      = max( maxRange / maxRGB, 1.0 );
72: 	D            = min( floor( D ) / 255.0, 1.0 );
73: 	return vec4( value.rgb * ( D * ( 255.0 / maxRange ) ), D );
74: }
75: const mat3 cLogLuvM = mat3( 0.2209, 0.3390, 0.4184, 0.1138, 0.6780, 0.7319, 0.0102, 0.1130, 0.2969 );
76: vec4 LinearToLogLuv( in vec4 value )  {
77: 	vec3 Xp_Y_XYZp = value.rgb * cLogLuvM;
78: 	Xp_Y_XYZp = max(Xp_Y_XYZp, vec3(1e-6, 1e-6, 1e-6));
79: 	vec4 vResult;
80: 	vResult.xy = Xp_Y_XYZp.xy / Xp_Y_XYZp.z;
81: 	float Le = 2.0 * log2(Xp_Y_XYZp.y) + 127.0;
82: 	vResult.w = fract(Le);
83: 	vResult.z = (Le - (floor(vResult.w*255.0))/255.0)/255.0;
84: 	return vResult;
85: }
86: const mat3 cLogLuvInverseM = mat3( 6.0014, -2.7008, -1.7996, -1.3320, 3.1029, -5.7721, 0.3008, -1.0882, 5.6268 );
87: vec4 LogLuvToLinear( in vec4 value ) {
88: 	float Le = value.z * 255.0 + value.w;
89: 	vec3 Xp_Y_XYZp;
90: 	Xp_Y_XYZp.y = exp2((Le - 127.0) / 2.0);
91: 	Xp_Y_XYZp.z = Xp_Y_XYZp.y / value.y;
92: 	Xp_Y_XYZp.x = value.x * Xp_Y_XYZp.z;
93: 	vec3 vRGB = Xp_Y_XYZp.rgb * cLogLuvInverseM;
94: 	return vec4( max(vRGB, 0.0), 1.0 );
95: }
96: 
97: vec4 mapTexelToLinear( vec4 value ) { return LinearToLinear( value ); }
98: vec4 envMapTexelToLinear( vec4 value ) { return LinearToLinear( value ); }
99: vec4 emissiveMapTexelToLinear( vec4 value ) { return LinearToLinear( value ); }
100: vec4 linearToOutputTexel( vec4 value ) { return LinearToLinear( value ); }
101: 
102: uniform sampler2D texture;
103: uniform vec4 backgroundColor;
104: varying vec2 vUv;
105: void main() {
106:   vec4 sample = texture2D(texture, vUv);
107:   if (sample.a > 0.0) {
108:     vec3 diffuse = (sample.rgb * sample.a) + (backgroundColor.rgb * (1.0 - sample.a));
109:     gl_FragColor = vec4(diffuse, (backgroundColor.a >= 0.5) ? 1.0 : sample.a);
110:   } else {
111:     if (backgroundColor.a >= 0.5) {
112:       gl_FragColor = backgroundColor;
113:     } else {
114:       discard;
115:     }
116:   }
117: }  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() vertex WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshBasicMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define USE_FOG
8: #define FOG_EXP2
9: #define USE_MAP
10: #define BONE_TEXTURE
11: #define DOUBLE_SIDED
12: #define NUM_CLIPPING_PLANES 0
13: uniform mat4 modelMatrix;
14: uniform mat4 modelViewMatrix;
15: uniform mat4 projectionMatrix;
16: uniform mat4 viewMatrix;
17: uniform mat3 normalMatrix;
18: uniform vec3 cameraPosition;
19: attribute vec3 position;
20: attribute vec3 normal;
21: attribute vec2 uv;
22: #ifdef USE_COLOR
23: 	attribute vec3 color;
24: #endif
25: #ifdef USE_MORPHTARGETS
26: 	attribute vec3 morphTarget0;
27: 	attribute vec3 morphTarget1;
28: 	attribute vec3 morphTarget2;
29: 	attribute vec3 morphTarget3;
30: 	#ifdef USE_MORPHNORMALS
31: 		attribute vec3 morphNormal0;
32: 		attribute vec3 morphNormal1;
33: 		attribute vec3 morphNormal2;
34: 		attribute vec3 morphNormal3;
35: 	#else
36: 		attribute v[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshBasicMaterial
4: #define GAMMA_FACTOR 2
5: #define USE_FOG
6: #define FOG_EXP2
7: #define USE_MAP
8: #define DOUBLE_SIDED
9: #define NUM_CLIPPING_PLANES 0
10: #define UNION_CLIPPING_PLANES 0
11: uniform mat4 viewMatrix;
12: uniform vec3 cameraPosition;
13: #define TONE_MAPPING
14: #define saturate(a) clamp( a, 0.0, 1.0 )
15: uniform float toneMappingExposure;
16: uniform float toneMappingWhitePoint;
17: vec3 LinearToneMapping( vec3 color ) {
18: 	return toneMappingExposure * color;
19: }
20: vec3 ReinhardToneMapping( vec3 color ) {
21: 	color *= toneMappingExposure;
22: 	return saturate( color / ( vec3( 1.0 ) + color ) );
23: }
24: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
25: vec3 Uncharted2ToneMapping( vec3 color ) {
26: 	color *= toneMappingExposure;
27: 	return saturate( Uncharted2Helper( […]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() vertex WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshBasicMaterial
4: #define VERTEX_TEXTURES
5: #define GAMMA_FACTOR 2
6: #define MAX_BONES 0
7: #define USE_FOG
8: #define FOG_EXP2
9: #define USE_MAP
10: #define BONE_TEXTURE
11: #define DOUBLE_SIDED
12: #define NUM_CLIPPING_PLANES 0
13: uniform mat4 modelMatrix;
14: uniform mat4 modelViewMatrix;
15: uniform mat4 projectionMatrix;
16: uniform mat4 viewMatrix;
17: uniform mat3 normalMatrix;
18: uniform vec3 cameraPosition;
19: attribute vec3 position;
20: attribute vec3 normal;
21: attribute vec2 uv;
22: #ifdef USE_COLOR
23: 	attribute vec3 color;
24: #endif
25: #ifdef USE_MORPHTARGETS
26: 	attribute vec3 morphTarget0;
27: 	attribute vec3 morphTarget1;
28: 	attribute vec3 morphTarget2;
29: 	attribute vec3 morphTarget3;
30: 	#ifdef USE_MORPHNORMALS
31: 		attribute vec3 morphNormal0;
32: 		attribute vec3 morphNormal1;
33: 		attribute vec3 morphNormal2;
34: 		attribute vec3 morphNormal3;
35: 	#else
36: 		attribute v[…]  three.js:17041:4
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
 1: precision highp float;
2: precision highp int;
3: #define SHADER_NAME MeshBasicMaterial
4: #define ALPHATEST 0.5
5: #define GAMMA_FACTOR 2
6: #define USE_FOG
7: #define FOG_EXP2
8: #define USE_MAP
9: #define DOUBLE_SIDED
10: #define NUM_CLIPPING_PLANES 0
11: #define UNION_CLIPPING_PLANES 0
12: uniform mat4 viewMatrix;
13: uniform vec3 cameraPosition;
14: #define TONE_MAPPING
15: #define saturate(a) clamp( a, 0.0, 1.0 )
16: uniform float toneMappingExposure;
17: uniform float toneMappingWhitePoint;
18: vec3 LinearToneMapping( vec3 color ) {
19: 	return toneMappingExposure * color;
20: }
21: vec3 ReinhardToneMapping( vec3 color ) {
22: 	color *= toneMappingExposure;
23: 	return saturate( color / ( vec3( 1.0 ) + color ) );
24: }
25: #define Uncharted2Helper( x ) max( ( ( x * ( 0.15 * x + 0.10 * 0.50 ) + 0.20 * 0.02 ) / ( x * ( 0.15 * x + 0.50 ) + 0.20 * 0.30 ) ) - 0.02 / 0.30, vec3( 0.0 ) )
26: vec3 Uncharted2ToneMapping( vec3 color ) {
27: 	color *= toneMappingExposure;
28: 	return sa[…]  three.js:17041:4
app started  index.js:5:5
TypeError: NetworkError when attempting to fetch resource.  _core_engines_config.js:360:13
TypeError: NetworkError when attempting to fetch resource.  (unknown)
TypeError: NetworkError when attempting to fetch resource.  _core_engines_config.js:399:15
unreachable code after return statement[Learn More]  _core_engines_wallet.js:965:12
TypeError: NetworkError when attempting to fetch resource.  _core_engines_servers.js:356:19
```

**Comment by avaer** [comment]
Thanks -- so, it looks like everything's working, but the browser is blacklisting some WebGL features on that GPU, so certain shaders aren't drawing.

This can happen when either the GPU doesn't support some features (common on older/integrated graphics cards), or it could be a driver problem, or browser bugs.

```
Error: WebGL warning: Disallowing antialiased backbuffers due to blacklisting.
...
THREE.WebGLShader: gl.getShaderInfoLog() fragment WARNING: 0:1: extension 'GL_ARB_gpu_shader5' is not supported
```

If the GPU is relatively recent, it might be helpful to check out http://webglreport.com/?v=1 or figure out why the browser thinks it should be blacklisted. I know some linux drivers have caused me headaches in the past.

For my part, I'll open an issue for doing a better job detecting this and warning that the browser reports not supporting the required WebGL features. It should be front and center and we shouldn't have to open the console to find out that's the problem.

However, I'm not sure if this can be made to work without rewriting shaders to use less features, not use antialiasing, and so on. If anyone wants to contribute that, that would be amazing, and probably not too much work; I'd gladly provide guidance. But it would be a challenge to do that without having a GPU setup that repros.

**Comment by PeteBoucher** [comment]
Yeah, I'm running an old Mac Pro with the stock ATI Radeon HD 2600 XT 256 MB

I'm considering upgrading to a graphics card that supports at least openGL 3.1. I'll let you know.

Thanks for the diagnostics.

**Pull request merged**
